spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:file:./WUD-Games-Database}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lio6fxrWQDzdEIva
            clientSecret: 619a4e33aac5333b3cde736c60abc213149bedae
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      RentalRequestCheckoutRecordUnique: RENTAL_REQUEST_CHECKOUT_RECORD_UNIQUE
