# Note the docker container will need to be deleted ($docker rm wud-games-website-elasticsearch-1) before changes to this file will apply
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:9.3.3'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - 9200:9200
      - 9300:9300

